### ISSUE TITLE
No option to interact

### ISSUE THREAD

**Issue by EivTBH** [miki4920/RimDungeon_Traps#1] opened 2022-02-14 13:54 UTC
I have posted on steam comments of the mod. The issue is the same as another issue and wont allow any way to interact with the traps except to choose what gas to use. It does allow you to click "Re-Arm" but if you right click, it has no options.

I have turned off all mods and it works so it has to be a conflict. I've attached my modlist to see if that helps

[modlist.txt](https://github.com/miki4920/RimDungeon_Traps/files/8061246/modlist.txt)
.

**Comment by mikolajg-tt** [comment] 2022-02-15 09:59
I will have a look through modlist and determine the conflict. The fix should be done by Sunday, assuming the issue does not force me to rewrite the mod.

**Comment by EivTBH** [comment] 2022-02-15 10:00
Appreciate the prompt response. Take your time, no rush :)

**Comment by mikolajg-tt** [comment] 2022-02-18 12:04
I am unable to reproduce the bug. As such, I have few additional questions:
- What RimWorld version are you using?
- Does the order of modlist reflect your order in game? If not, could you post a mod string from the modmanager?
- Could you send a screenshots showing parts of interface that are missing?

**Comment by EivTBH** [comment] 2022-02-18 18:30
Version # is 1.3.3200 (64bit)


I have moved it around the mod order. It's been after the official content to right at the bottom of the load order. Neither fixed it.

In regards to the parts that are missing, I don't have any screenshots but its the context menu when you right click.

I wouldn't worry about it mate. It seems to be such a niche issue that It's not worth your time and effort.

I appreciate you looking into it though.

**Comment by mikolajg-tt** [comment] 2022-02-18 19:35
Sure, I will close the issue for now. I will look into it again if more people end up suffering from it though.

**Closed as completed by mikolajg-tt** 2022-02-18 19:35 UTC
